# Generated by Django 4.1.6 on 2023-03-08 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('price', models.IntegerField(blank=True, verbose_name='Price')),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('release_date', models.DateField(blank=True, verbose_name='Release')),
                ('lte_exists', models.BooleanField(verbose_name='LTE')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
            ],
        ),
    ]
